/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class SuccessStoryModel
	{
        public string Title { get; set; }
        public string Description { get; set; }
        public string SummaryDescription { get; set; }
        public string Company { get; set; }
        public string CompanyWebsite { get; set; }
        public string Industry { get; set; }
        public string ProductsUsed { get; set; }
        public string Thumbnail { get; set; }
	}
}